.PHONY: clean All

All:
	@echo "----------Building project:[ 51 - Debug ]----------"
	@cd "51" && "$(MAKE)" -f  "51.mk"
clean:
	@echo "----------Cleaning project:[ 51 - Debug ]----------"
	@cd "51" && "$(MAKE)" -f  "51.mk" clean
