.PHONY: clean All

All:
	@echo "----------Building project:[ 50 - Debug ]----------"
	@cd "50" && "$(MAKE)" -f  "50.mk"
clean:
	@echo "----------Cleaning project:[ 50 - Debug ]----------"
	@cd "50" && "$(MAKE)" -f  "50.mk" clean
