.PHONY: clean All

All:
	@echo "----------Building project:[ TemplateProject - Debug ]----------"
	@cd "Project1" && "$(MAKE)" -f  "TemplateProject.mk"
clean:
	@echo "----------Cleaning project:[ TemplateProject - Debug ]----------"
	@cd "Project1" && "$(MAKE)" -f  "TemplateProject.mk" clean
